### ISSUE TITLE
can't "make" when installing yap (5th step)

### ISSUE THREAD

**Issue by YantianZha** [davidenitti/DC#1]
I got stucked at the 5th step of:
cd yap-6.3
mkdir arch
cd arch
../configure --enable-tabling=yes --enable-dynamic-loading
make
sudo make install
sudo make install_library

Output:
config.status: creating packages/clpqr/Makefile
config.status: creating packages/swi-minisat2/Makefile
config.status: creating packages/swi-minisat2/C/Makefile
config.status: creating packages/real/Makefile
config.status: creating packages/real/rconfig.h
config.status: creating packages/myddas/Makefile
config.status: creating packages/CLPBN/Makefile
config.status: creating packages/CLPBN/horus/Makefile
config.status: creating packages/prism/src/c/Makefile
config.status: creating packages/prism/src/prolog/Makefile
config.status: creating packages/yap-lbfgs/Makefile
config.status: creating config.h
config.status: creating YapTermConfig.h
config.status: YapTermConfig.h is unchanged
config.status: creating packages/raptor/raptor_config.h
config.status: packages/raptor/raptor_config.h is unchanged
yantian@yantian-Inspiron-7348:~/yap-6.3-master/arch$ make
make: **\* No rule to make target `H/dglobals.h', needed by`yap'.  Stop.

Thanks!

**Comment by vscosta** [comment]
Dear Zha

Please have a look at the new README.md file.

Sorry.

Vitor

**Comment by YantianZha** [comment]
Thank you very much!

**Comment by ana-neto** [comment]
I'm having the same issue, when I run make I get this error:

make: *** No rule to make target `H/dglobals.h', needed by `yap'.  Stop.

**Comment by vscosta** [comment]
Thanks!
