### ISSUE TITLE
Program gives permission error on abolish_all_tables

### ISSUE THREAD

**Issue by nunomen** [davidenitti/DC#3]
Everytime I run any provided example, like `yap -L examples/example1.pl`, I get this permission error:

 `ERROR!!  (/home/littlebrat/Git/DC/distributionalclause.pl:70).`

 `PERMISSION ERROR- in line 70, system predicate abolish_all_tables: modifying static procedure abolish_all_tables/0`

`Absolute error drawn(1) ~= 1: 0.00138055555555389`
`Absolute error drawn(1) ~= 2: 0.00197777777777297`
`Absolute error drawn(1) ~= 3: 0.00067246031746343`
`Absolute error average g ~ Gaussian(0,0.1): 0.0018059877648761`
`% 0.176 CPU in 0.179 seconds ( 98% CPU)`

I tried running it as a super user, but it also returns the same error. Is this expected behavior?

**Comment by davidenitti** [comment]
it's expected (and harmless), the user powers are irrelevant. I'll fix that asap.
in any case, it is sufficient to comment (or remove):

```
abolish_all_tables :-!.
```

https://github.com/davidenitti/DC/blob/master/distributionalclause.pl#L70

**Comment by davidenitti** [comment]
fixed, do an update of the code (git pull)

**Comment by nunomen** [comment]
Solved, thanks! :+1:
