### ISSUE TITLE
Problem implementing aggregation functions in DC

### ISSUE THREAD

**Issue by niteshroyal** [davidenitti/DC#4]
I am implementing an aggregation function in DC. The problem is that the head of the DC clause is not firing (the head random variable is not drawn from the probability distribution) when the body of the clause is true.  The DC code is below:
 
------------------------------------------------
%%% -*- Mode: Prolog; -*-
:- use_module('../DC/dcpf.pl').
:- use_module('../DC/random/sampling.pl').
:- use_module('../DC/distributionalclause.pl').
:- use_module(library(lists)).
:- use_module(library(random)).

:- set_options(default).
:- set_inference(backward(lazy)).
:- initialization(init).

builtin(lmax( _ , _ )).
builtin(oneElementOfList( _ , _ )).

% Randomly picks one element of the list.
oneElementOfList([], []).
oneElementOfList(List, Elt) :- length(List, Length), random(0, Length, Index), nth0(Index, List, Elt).

% Finds a element occuring the most number of times in the list. 
lmax(L, M) :- lmax(L, [], [], M).
lmax([], Seen, MMax, Max) :- MMax=[] -> Max=Seen; lmax(MMax, [], [], Max).
lmax([H|T], Seen, MMax, Max) :- (member(H, Seen) -> lmax(T, Seen, [H|MMax], Max); lmax(T, [H|Seen], MMax, Max)).
maxMod(X, P) ~ val(Max) := findall_forward(X,P,L), lmax(L, Max1), oneElementOfList(Max1, Max).

% Facts
marks(ann, bio) ~ val(high).
marks(ann, chem) ~ val(high).
marks(ann, phy) ~ val(low).

% Rule
grade(S) ~ finite([0.1:low, 0.9:high]) := maxMod(M, marks(S,C) ~= M) ~= high.

% Find probabilities 
testMod(N) :- 
	query([],[],(maxMod(M, marks(ann,C) ~= M) ~= high),N,P), 
	write('probability: '),writeln(P).

testGrade(N) :- 
	query([],[],(grade(ann) ~= high),N,P), 
	write('probability: '),writeln(P).

-------------------------------------------------------------------

After executing the above code I get 
?- testMod(100).
probability: 1.0
   
?- testGrade(100).
probability: 0.0

Which means that the body is the clause "grade(S) ~ finite([0.1:low, 0.9:high]) := maxMod(M, marks(S,C) ~= M) ~= high." is always true but the head never fires. 

I have invested a lot of time in resolving the issue but was not successful. Can you please check the issue?

**Comment by davidenitti** [comment]
the syntax `maxMod(M, marks(S,C) ~= M) ~= high` and `maxMod(M, marks(ann,C) ~= M) ~= high` seems wrong.
the second argument of maxMod should be a term or a variable, you set an equality `marks(S,C) ~= M`, I don't understand it. This type of use was not contemplated, even though it might run (I don't know the behavior of this in practice).
what are you trying to do? 
another note: I would not use random directly, I would use a DC rule with uniform distribution, where the elements are the list.
by the way this DC https://bitbucket.org/problog/dc_problog might be a bit more updated (but I don't maintain it)

**Comment by niteshroyal** [comment]
I have found that the issue is a bit more severe. Let's consider the DC program:

-----------------------------------------------------------------------------------------------------
friend(X,Y) ~ finite([0.9:true, 0.1:false]) := true.
smokes(X) ~ finite([0.2:true, 0.8:false]) := friend(X,Y)~=true.

test(N) :-
	    init,
	    query([],[],(smokes(ann)~=true),N,P),
	    write('probability: '),writeln(P).

------------------------------------------------------------------------------------------------------
When I execute this, I get: 

?- test(1000).
probability: 0.0

The answer is wrong. But when I replace 2nd clause of the program by:
smokes(X) ~ finite([0.2:true, 0.8:false]) := friend(X,bob)~=true.
I get:

?- test(1000).
probability: 0.179999999999998

In this case, the answer is correct. 

Is it the case that the body of the clause in DC should always be grounded? If this is the case then it is serious problem I guess. Consider the following Prolog program. 

-------------------------------------------------------------------------------------------------------
friend(X,Y) :- true.
smokes(X) :- friend(X,Y).

-------------------------------------------------------------------------------------------------------

When I execute this, I get

?- smokes(ann).
yes


I was facing the problem because DC is not able to handle non-grounded clauses. If I replace clauses in the program mentioned in my previous comment by: 

maxMod(L) ~ val(Max) :=  lmax(L, Max1), oneElementOfList(Max1, Max).
grade(S) ~ finite([0.1:low, 0.9:high]) := findall_forward(M,  marks(S,C) ~= M, L), maxMod(L) ~= high.

Then everything works fine. 
This kind of aggregation function performs aggregation over random variables. Here marks of the students are random variables. I need these kinds of aggregation functions. Currently, my problem is solved if I write the functions like the way mentioned above.

**Comment by davidenitti** [comment]
the probabilistic model described in DC is not well defined:
```
friend(X,Y) ~ finite([0.9:true, 0.1:false]) := true.
smokes(X) ~ finite([0.2:true, 0.8:false]) := friend(X,Y)~=true.
```
it's not about DC inference limitations.
The problem is the following: the second rule says that X smokes with prob 0.2 only if it has a friend. (if X does not have a friend, smokes(X) is not even defined).
Now how many people there are? if there are an infinite number of people it means that there are random variables friend(ann,Y) for each Y (e.g. for each natural number), so at least one will be true (because there are infinitely many).
if there is only 1 person then things are different and so on.
so the model is not well defined, because the number of possible Y is not defined.
allowing for non-ground variables would actually produce a wrong result, because the model is ill posed!

a solution, define the number of possible people as integers:
`friend(X,Y) ~ finite([0.9:true, 0.1:false]) := between(1,3,Y).`

or define explicitly the people person(ann), person(bob) and use:
`friend(X,Y) ~ finite([0.9:true, 0.1:false]) := person(Y).`

is this more clear?

**Comment by niteshroyal** [comment]
Yes, it is clear. Thanks.
